### ISSUE TITLE
Make result of "bathingspot" request consistent

### ISSUE THREAD

**Issue by hsonne** [technologiestiftung/flusshygiene-postgres-api#106]
The request "bathingspots" (without user_id or bathingspot_id) does not return the same data structure (with slots "data", "message", "success", "apiVersion") as the requests that set a user_id or both user_id and bathingspot_id. @fabianmoronzirfas Could you make this consistent or is there a reason for the difference?

Request "bathingspots" returns:
```
List of 2451
  ..$ :List of 52
  ..$ :List of 52
  ..$ :List of 52
  .. [list output truncated]
```

Request "users/3/bathingspots" returns:
```
List of 4
  ..$ data      :List of 2451
  ..$ message   : chr "Everything OK"
  ..$ success   : logi TRUE
  ..$ apiVersion: chr "1.3.9-dev"
```

Request "users/3/bathingspots/18" returns:
```
List of 4
  ..$ data      :List of 1
  ..$ message   : chr "Everything OK"
  ..$ success   : logi TRUE
  ..$ apiVersion: chr "1.3.9-dev"
```

**Comment by fabianmoronzirfas** [comment]
Done with deploy of api version v1.4.0-dev

**Comment by fabianmoronzirfas** [comment]
@hsonne ☝️
