### ISSUE TITLE
Let Get model not return the big fields

### ISSUE THREAD

**Issue by hsonne** [technologiestiftung/flusshygiene-postgres-api#114]
As we store a very long text (a few megabytes) in field `rmodel` we should exclude this field from the result when asking for all models at a bathing spot, e.g. when requesting

```
users/3/bathingspots/18/models
```
Otherwise the result set will become very big as soon as there are several models stored for one and the same bathing spot. I think that this request should just give an overview on available models for which the fields `id`, `createdAt`, `version`, `updatedAt`, `comment` are the most relevant.

Only if a specific model is requested, e.g. with
```
users/3/bathingspots/18/models/30
```

the field `rmodel` should be included in the result. 

Or what do you think, @fabianmoronzirfas?

**Comment by fabianmoronzirfas** [comment]
Sounds good. We soon will also have to do the upload of the models in a different way.

**Comment by fabianmoronzirfas** [comment]
@hsonne api v1.6.0 does not return all the `rmodels` and `rmodelBinary` on call to `bathingpsot/${id}/models`. Call must be explicit with id of that model
