### ISSUE TITLE
Change latitude and longitude

### ISSUE THREAD

**Issue by hsonne** [technologiestiftung/flusshygiene-postgres-api#132]
The fields latitude and longitude are interchanged in the postgres database (see example below)!

![latlong_berlin](https://user-images.githubusercontent.com/11964315/63774216-10ff3880-c8dd-11e9-8efa-f5f6c718bf8b.png)
![latlong_postgres_badewiese](https://user-images.githubusercontent.com/11964315/63774218-10ff3880-c8dd-11e9-89b5-f9f4cfcfbc9b.png)

**Comment by fabianmoronzirfas** [comment]
😆 
```json
    "lat": "13.18595",
    "lng": "52.48418",
```

See --> https://github.com/technologiestiftung/flusshygiene-postgres-api/blob/master/data/badestellen-2019-06-17%2012-44-27.json

This is already coming in  sqlitedb from the badegewaesser-berlin.de page. @sebastian-meier 🚀

**Comment by fabianmoronzirfas** [comment]
<img width="1158" alt="Screenshot 2019-08-27 at 16 28 29" src="https://user-images.githubusercontent.com/315106/63779999-c46d2a80-c8e7-11e9-9233-2937284f4fd9.png">

**Comment by fabianmoronzirfas** [comment]
Data on server of badestellen-berlin.de is fixed with https://github.com/technologiestiftung/badestellen/commit/d960af493b8135086763e7febfd249c2aa76c0c6

**Comment by fabianmoronzirfas** [comment]
fixed.
