### ISSUE TITLE
Remove CustomRepositories. Will be removed in 0.4.0

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/flusshygiene-postgres-api#63]
https://github.com/typeorm/typeorm/issues/3251

**Comment by jshearer** [comment]
Where would you recommend putting custom query functionality that currently lives in custom repositories?

**Comment by fabianmoronzirfas** [comment]
Hi @jshearer. I will start writing simple helper functions. Like these https://github.com/technologiestiftung/flusshygiene-postgres-api/blob/master/src/lib/utils/repo-helpers.ts

In the end the CustomRepo is nothing more then that. Or is there something I missed?

**Comment by jshearer** [comment]
Oh man, I got very confused -- I thought this was the typeorm repo. My bad :)

**Comment by fabianmoronzirfas** [comment]
No problemo
