### ISSUE TITLE
Add new column to rmodel table to hold binary data (blob)

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/flusshygiene-postgres-api#94]
This is for testing purpose. We should actually post binary data into an S3 and reference it. Also needed for images.

**Comment by hsonne** [comment]
@fabianmoronzirfas I just tested to store a text representation of a model in the text column "rmodel" by posting to the API path `users/3/bathingspots/18/models`. I got the error: `413 Request Entity Too Large`. The text that I wanted to post to the API path  had a length of `4129955` bytes.

**Comment by fabianmoronzirfas** [comment]
Okay. Good to know. So we actual need to implement a storage somewhere else for large files like this.

**Comment by fabianmoronzirfas** [comment]
Or is is a problem with the nginx that is sitting infront of the API https://www.keycdn.com/support/413-request-entity-too-large

I'll investigate

**Comment by fabianmoronzirfas** [comment]
@hsonne I updated the config for the nginx gateway. It should allow uploads up to 10mb now.

**Comment by hsonne** [comment]
@fabianmoronzirfas I just tried to post different test strings. Length accepted seems to be at maximum about 100000 bytes (about 100kB). Is your change already in effect?

**Comment by fabianmoronzirfas** [comment]
@hsonne It was not only the nginx it is also the express server. An update will be live soon.

**Comment by fabianmoronzirfas** [comment]
@hsonne Fixed. You can now post up to 10mb

**Comment by fabianmoronzirfas** [comment]
Just as reminder. Here are some postgres types https://github.com/typeorm/typeorm/tree/master/test/functional/database-schema/column-types/postgres

**Comment by fabianmoronzirfas** [comment]
@hsonne next version of API v1.5.0 will have a binary field on the Model. We need to find out how to post to that.
